### ISSUE TITLE
Text selection within trapped element not possible if any ancestor has a `tabindex`

### ISSUE THREAD

**Issue by mkantor** [focus-trap/focus-trap#870] opened 2023-01-02 16:53 UTC
When an ancestor of the focus-trap container has a `tabindex` attribute set (even if its value is `-1`), it's not possible to select any text within the focus-trapped container. [Here's a demo](https://codesandbox.io/s/trusting-ully-blyjjn).

This seems to be because when the mouse button is pressed to begin selection, browsers fire a `focusin` event on the `tabindex`ed ancestor which is handled [here](https://github.com/focus-trap/focus-trap/blob/bd69c94147b591f779aeaeb26df564f8d1ee9d45/index.js#L624) during event capturing phase and [focus is moved](https://github.com/focus-trap/focus-trap/blob/bd69c94147b591f779aeaeb26df564f8d1ee9d45/index.js#L432-L434) even if the click would have been inside the focus trap.

I've reproduced the issue in these browsers on macOS 12.3:
- Firefox 108.0
- Chrome 108.0
- Safari 15.4

**Comment by mkantor** [comment] 2023-01-02 17:02
I don't understand why [`tryFocus` is called here](https://github.com/focus-trap/focus-trap/blob/bd69c94147b591f779aeaeb26df564f8d1ee9d45/index.js#L434) instead of only preventing the `focusin` event from propagating like the handlers for other types of events. I think removing that line will fix the issue, but I'm not sure if it causes other problems.

**Comment by stefcameron** [comment] 2023-01-04 19:23
> I don't understand why [tryFocus is called here](https://github.com/focus-trap/focus-trap/blob/bd69c94147b591f779aeaeb26df564f8d1ee9d45/index.js#L434) instead of only preventing the focusin event from propagating like the handlers for other types of events. I think removing that line will fix the issue, but I'm not sure if it causes other problems.

@mkantor Thank you for your analysis and for the demo. The `tryFocus()` is there because, so far in the implementation, we believe focus has escaped the trap, so we need to pull focus back _into_ the trap, and to do that, we have to try to focus something inside the trap (i.e. the most recently focused node, or the initial focus node).

So I can see that no matter the `tabindex` value (-1, 0, 1) of the trap's ancestor, text selection doesn't work. I'm guessing that's because making the div focusable means clicking anywhere inside it -- other than directly on a focusable child -- means it either triggers a click on the div, and because the div is not inside the trap, focus-trap determines focus has escaped and pulls focus back in with the `tryFocus()` in the else case.

Or, it triggers a click on the selectable text, but since it's not tabbable, it never gets registered in the trap's containers, which [we first search](https://github.com/focus-trap/focus-trap/blob/bd69c94147b591f779aeaeb26df564f8d1ee9d45/index.js#L424) and so again, we think focus has escaped and we need to pull it back in.

Given it's possible to select the text inside the trap when the ancestor div is not tabbable nor focusable (i.e. does not have a `tabindex` attribute), I'm guessing it's the first case: Click on non-tabbable/focusable text inside the ancestor div triggers click on the ancestor div (even with tabindex="-1", it's possible to set focus to it by clicking on it), leading focus-trap to detect trap escape, pulling focus back in.

That seems considerably harder to fix than if it were just the text not being in the trap's containers, which doesn't seem to be an issue when the ancestor div isn't tabbable/focusable since boilerplate text is never either. Simply selecting the text does not (I checked) trigger any change to the focus (doesn't trigger `focusIn` event, anyway), even though something that had focus inside the trap will lose its focus ring.

I modified the [default behavior demo](https://focus-trap.github.io/focus-trap/) to have a div with some text inside around the trap, same as in your demo. Note that the demo page is styled such that _anything_ that has focus has a big bold focus ring around it.

First is the "no tabindex" case, where you see that the div isn't focusable:

![focus-trap-issue-870-no-tabindex](https://user-images.githubusercontent.com/2855350/210631905-b112857c-5cd6-4d18-a744-baf7b0536711.gif)

And even though the focus ring disappears from the anchors when I select text inside the trap, the `focusIn` event is never fired. I guess the anchor _loses_ focus, but nothing _gains_ focus? Seems strange since focus should go to the document, but 🤷‍♂️ not sure where it goes or doesn't go.

Next is the "tabindex = -1" case where the div is focusable. Notice the difference when and _what_ things get focus:

![focus-trap-issue-870-tabindex-1](https://user-images.githubusercontent.com/2855350/210631998-8fd32fb8-9ceb-4bf0-9c77-cbe33a9df892.gif)

The fact the ancestor div is focusable clearly interferes with what stuff gets clicked on, and you can imagine that once the trap is activated, clicking on the text inside the trap now registers click on the ancestor div, leading to the `focusIn` event because it's focusable, leading focus-trap to detect a focus escape _even though_ you think you're just clicking on the text...

So all that to say... not a bug? What do you think? If you still think it's a focus-trap bug, how would you solve this?

**Comment by mkantor** [comment] 2023-01-04 21:44
Thanks for the detailed response!

> So all that to say... not a bug? What do you think? If you still think it's a focus-trap bug, how would you solve this?

I guess my first question is whether `focus-trap` is intentionally also trapping text selection or not. Your first screencap also demonstrates surprising behavior, now that I think about it: why shouldn't you be able to select the "ancestor div without tabindex" text? Doing so wouldn't _focus_ anything outside of the trap, after all. After some experimentation I see now that many interactions that have nothing to do with focus (like clicking on links or expanding/collapsing a `<details>` element) outside of the trap don't work.

If `focus-trap` is really more like `user-interaction-trap` then this behavior makes sense, but otherwise perhaps not.

Either way, it feels like _within_ the trap you shouldn't be prevented from doing things when the trap is activated that you could have done otherwise, so I'm inclined to think the issue I originally described is a bug no matter what your thoughts are on the above (or perhaps it's a "known limitation" if there isn't a reasonable fix... I'd have to dig deeper into the implementation to have informed thoughts). But it's possible the bug I described is just a specific narrow symptom of a bigger issue, like "focus-trap interferes with user interactions which wouldn't otherwise have caused elements outside the trap to become focused".

**Comment by mkantor** [comment] 2023-01-04 21:51
Or perhaps the intention is "at all times there must be an element within the `focus-trap` which has focus", in which case your first screencap demonstrates a different bug: the text inside there shouldn't be selectable in that scenario because doing so blurs all of the focusable elements.

**Comment by stefcameron** [comment] 2023-01-04 22:15
BTW, this is all I did to the demo in the `index.html` file:

Before:
```
        <div id="default" class="trap">
          <p>
            Here is a focus trap <a href="#">with</a> <a href="#">some</a> <a href="#">focusable</a> parts.
          </p>
          <p>
            <button id="deactivate-default" aria-describedby="default-heading">
              deactivate trap
            </button>
          </p>
        </div>
```

After:
```
      <div id="tabindex-test" style="border: 1px solid red; padding: 10px">
        ancestor div without tabindex
        <div id="default" class="trap">
          <p>
            Here is a focus trap <a href="#">with</a> <a href="#">some</a> <a href="#">focusable</a> parts.
          </p>
          <p>
            <button id="deactivate-default" aria-describedby="default-heading">
              deactivate trap
            </button>
          </p>
        </div>
      </div>
```

**Comment by stefcameron** [comment] 2023-01-18 15:00
I will close this issue now. I think the problem is ultimately with the way things work in HTML with parent elements where the parent is focusable and contains stuff you're also expecting the user to interact with (i.e. a focusable parent that contains focusable children).

**Closed by stefcameron** 2023-01-18 15:00 UTC

**Comment by mkantor** [comment] 2023-01-18 15:29
Apologies for losing track of this issue, but closing it seems fine. I may dig more deeply into the implementation at some point and if I come up with any ideas I'll open pull requests (and/or reopen this issue if discussion seems warranted).

Thanks again for being super responsive, and also for teaching me about the existence of `inert`—seems like that will be handy once it's more widely-supported (I've also had my eyes on `<dialog>` which I think might obviate the use cases we have for `focus-trap`, but migrating to it will be a pain).

**Comment by stefcameron** [comment] 2023-01-18 15:43
> Apologies for losing track of this issue, but closing it seems fine. I may dig more deeply into the implementation at some point and if I come up with any ideas I'll open pull requests (and/or reopen this issue if discussion seems warranted).

Sounds great!

> Thanks again for being super responsive, and also for teaching me about the existence of inert—seems like that will be handy once it's more widely-supported (I've also had my eyes on <dialog> which I think might obviate the use cases we have for focus-trap, but migrating to it will be a pain).

👍
