### ISSUE TITLE
Feature request: add nextFocusKey and previousFocusKey props

### ISSUE THREAD

**Issue by jblevins1991** [focus-trap/focus-trap#612] opened 2022-02-01 19:01 UTC
A focus trap is normally used to keep focus in a dropdown or modal while a user is using that element. In scenarios of a dropdown or autocomplete using the TrapFocus component, there is no way to change which keyCodes move the focus to the next or previous elements in the trap, but in the ADA documentation, the keys to do this in autocompletes and dropdowns are the arrow keys.

**Comment by jblevins1991** [comment] 2022-02-15 12:20
Thank you for considering my request and adding visibility to it as well.

**Comment by jrnail23** [comment] 2022-10-31 08:39
@stefcameron , I see this was closed by @jblevins1991 , but I don't see any actual resolution to the request. I'm also looking to address a similar use-case to what's being requested here.  Can this issue be reopened?

**Comment by stefcameron** [comment] 2022-10-31 15:33
@jrnail23 You're correct, the issue was closed without a new feature being added to address it. We can certainly re-open it. Did you have any ideas on how it should be implemented? Maybe even a PR for it?

What would you think if it was done by adding 2 new options: `isTabForward(event: KeyboardEvent): boolean` and `isTabBackward(event: KeyboardEvent): boolean`. These would default to `TAB` and `SHIFT+TAB` internally, but you could override them to be whatever key sequences you want, like arrow forward/backward.

Alternately, it could be done through a single option like `keyboardNav: { forwardKey: { altKey: boolean, metaKey: boolean, ctrlKey: boolean, shiftKey: boolean, key: string }, backwardKey: {...} }` but the disadvantage I see of this over the functions is that in this case, we might be leaving out some property of the `KeyboardEvent` that the user wants to configure or check for, and it's predetermined. With the functions, you can change what keys are used at runtime if you want.

**Comment by stefcameron** [comment] 2022-11-08 03:48
Looking for feedback, lest the issue is closed again.

**Comment by jrnail23** [comment] 2022-11-14 21:41
@stefcameron  I think either of those could be workable... the first is probably better, for the same reasons you mentioned. The functions would likely be more flexible and powerful.

**Comment by stefcameron** [comment] 2022-11-30 19:48
@jrnail23 @jblevins1991 PR is open here: https://github.com/focus-trap/focus-trap/pull/847

**Closed** 2022-12-02 03:55 UTC

**Comment by stefcameron** [comment] 2022-12-02 14:42
Published in 7.2.0
